language: node_js
sudo: false
dist: trusty

node_js:
  - '8'

addons:
  chrome: stable

before_script:
  - npm install

stages:
  - test
  - deploy
  - release
jobs:
  include:
    - env: "PHASE=lint"
    - env: "PHASE=aot"
    - env: "PHASE=unit"
    - env: "PHASE=lib_build"
    - stage: test
      script: ./scripts/travis-script.sh
    - stage: deploy
      script: npm run lib:build
      deploy:
        provider: azure_web_apps
        file: lib/deploy/*
        skip_cleanup: true
        on: 
          branch: travis-deploy

cache:
  directories:
    - ./node_modules/


