language: node_js
sudo: false
dist: trusty

node_js:
  - '8'

addons:
  chrome: stable

before_script:
  - npm install

stages:
  - install
  - test
  - deploy
  - release
jobs:
  include:
    - stage: test
      script: npm run lint
      script: npm run ci:build
      script: npm run ci:test
    - stage: deploy
      script: npm run lib:build
      deploy:
        provider: azure_web_apps
        file: lib/deploy/*
        skip_cleanup: true

cache:
  directories:
    - ./node_modules/


